service_name: travis-pro
repo_token: 5bMsdtZcHtCeUKBeWbuNH4NPrGdbGzdOi

language: python

python:
    - "3.5

install:
    - pip install coveralls

script:
    - coverage run -m unittest

after_success:
    - coveralls
